;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	comment-dwim
	electric-newline-and-maybe-indent
	electric-pair-delete-pair
	eval-print-last-sexp
	helm-M-x
	indent-for-tab-command
	repeat
	))

(setq mc/cmds-to-run-once
      '(
	describe-key
	set-goal-column
	))
